//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stomatoloska.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class stomatoloskaEntities1 : DbContext
    {
        public stomatoloskaEntities1()
            : base("name=stomatoloskaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tRadnoVrijeme> tRadnoVrijeme { get; set; }
        public virtual DbSet<tZahvat> tZahvat { get; set; }
    }
}
