//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stomatoloska.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tZahvat
    {
        public int sifra { get; set; }
        public string naziv { get; set; }
        public decimal cijena { get; set; }
        public int trajanje_minuta { get; set; }
        public System.DateTime dcr { get; set; }
    }
}
