//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stomatoloska.DAL.Baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Narudzba
    {
        public int narudzba_id { get; set; }
        public System.DateTime termin_pocetak { get; set; }
        public System.DateTime termin_kraj { get; set; }
        public string status { get; set; }
        public int pacijent_id { get; set; }
        public int zahvat_id { get; set; }
        public System.DateTime dcr { get; set; }
        public int radno_vrijeme_id { get; set; }
    
        public virtual Pacijent Pacijent { get; set; }
        public virtual RadnoVrijeme RadnoVrijeme { get; set; }
        public virtual Zahvat Zahvat { get; set; }
    }
}
