//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stomatoloska.DAL.Baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacijent
    {
        public int pacijent_id { get; set; }
        public string prezime { get; set; }
        public string ime { get; set; }
        public System.DateTime datum_rodjenja { get; set; }
        public string telefon { get; set; }
        public string adresa { get; set; }
    }
}
