//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stomatoloska.DAL.Baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class RadnoVrijeme
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RadnoVrijeme()
        {
            this.tNarudzba = new HashSet<Narudzba>();
        }
    
        public int radno_vrijeme_id { get; set; }
        public string radni_dan { get; set; }
        public System.TimeSpan pocetak { get; set; }
        public System.TimeSpan kraj { get; set; }
        public System.DateTime dcr { get; set; }
        public System.DateTime od_datuma { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Narudzba> tNarudzba { get; set; }
    }
}
