//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stomatoloska.DAL.Baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zahvat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zahvat()
        {
            this.tNarudzba = new HashSet<Narudzba>();
        }
    
        public int zahvat_id { get; set; }
        public string sifra { get; set; }
        public string naziv { get; set; }
        public decimal cijena { get; set; }
        public int trajanje_minuta { get; set; }
        public System.DateTime dcr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Narudzba> tNarudzba { get; set; }
    }
}
